### ISSUE TITLE
关机还不行

### ISSUE THREAD

**Issue by dankey** [3dudu/dell-optiplex-7080-hackintosh-opencore#2]
点关机，CPU风扇狂转，不断电。

**Comment by 3dudu** [comment]
关机一开始安装时也不行，后来对照官方文档，都用最新的，再改改配置文件就好了。

**Comment by dankey** [comment]
你这个关机的更新了吗？更新一下吧，我就直接用你的了。

DP 接4K显示器 只能输出2K
framebuffer-stolenmem 设置成了 00003001
一删除这个，就起不来。
bios里面dvmt只能设到64M

**Comment by 3dudu** [comment]
我是708mff哦，bios没有改的话不能设置dvmt，我没有4k显示器，这个efi是能正常关机的，但具体是哪个配置项或补丁起作用的我也不知道，基本就是参考官方文档改的，下的acpi，扩张kext用最新的。

**Comment by lotsztai** [comment]
你应该是第一个搞7080的了，赞！
ps。我是7080mt，关机补丁我推荐这个，试试看：
[SSDT-SHUT.dsl.zip](https://github.com/3dudu/dell-optiplex-7080-hackintosh-opencore/files/5646861/SSDT-SHUT.dsl.zip)

**Comment by ghost** [comment]
> 点关机，CPU风扇狂转，不断电。

我整了一个关机补丁，试一下
[SSDT-SHUT.zip](https://github.com/3dudu/dell-optiplex-7080-hackintosh-opencore/files/5648354/SSDT-SHUT.zip)

同时要在config里面改名：
Find:     5F50545301
Replace:  5A50545301
![螢幕截圖 2020-12-06 下午1 46 49](https://user-images.githubusercontent.com/75524639/101272701-94d6ee80-37c9-11eb-9dbf-22821740a3a1.png)

ps。我是7080mt

**Comment by gushandujian** [comment]
> > 点关机，CPU风扇狂转，不断电。
> 
> 我整了一个关机补丁，试一下
> [SSDT-SHUT.zip](https://github.com/3dudu/dell-optiplex-7080-hackintosh-opencore/files/5648354/SSDT-SHUT.zip)
> 
> 同时要在config里面改名：
> Find: 5F50545301
> Replace: 5A50545301
> ![螢幕截圖 2020-12-06 下午1 46 49](https://user-images.githubusercontent.com/75524639/101272701-94d6ee80-37c9-11eb-9dbf-22821740a3a1.png)
> 
> ps。我是7080mt
我的电脑是7080mff，这个补丁可以关机，我的重启还不正常，重启变成关机了，我的CPU是I5 10500T，

**Comment by dankey** [comment]
> > 点关机，CPU风扇狂转，不断电。
> 
> 我整了一个关机补丁，试一下
> [SSDT-SHUT.zip](https://github.com/3dudu/dell-optiplex-7080-hackintosh-opencore/files/5648354/SSDT-SHUT.zip)
> 
> 同时要在config里面改名：
> Find: 5F50545301
> Replace: 5A50545301
> ![螢幕截圖 2020-12-06 下午1 46 49](https://user-images.githubusercontent.com/75524639/101272701-94d6ee80-37c9-11eb-9dbf-22821740a3a1.png)
> 
> ps。我是7080mt

可以正常关机了。非常感谢。
现在就差睡眠和耳机切换了。

**Comment by gushandujian** [comment]
> 可以正常关机了。非常感谢。
> 现在就差睡眠和耳机切换了。
你的视频播放正常不？我的打开腾讯视频、哔哩哔哩视频都无法正常播放，估计其他的都一样，显卡显示1536，感觉也正常，不知道哪出问题了

**Comment by dankey** [comment]
> > 可以正常关机了。非常感谢。
> > 现在就差睡眠和耳机切换了。
> > 你的视频播放正常不？我的打开腾讯视频、哔哩哔哩视频都无法正常播放，估计其他的都一样，显卡显示1536，感觉也正常，不知道哪出问题了

可以正常播放，没有问题啊。显存也是1536MB

**Comment by liuaerostone** [comment]
一直失败，怀疑是bios设置的问题，有什么注意事项么

**Comment by 3dudu** [comment]
> 一直失败，怀疑是bios设置的问题，有什么注意事项么

我的BIOS，供参考

SATA Operation : AHCI
Integrated NIC : Enabled
Secure Boot Enable : unChecked
Secure Boot Mode : Audit Mode
SGX : Disabled
SpeedStep : Enable
C-States Control : Checked
Turboost : Enable
HyperThread Control : Enable
Intel Speed Shift Technology : Enable
Deep Sleep Control : Disabled
USB Wake Support : unChecked
Wake on LAN/WLAN : Lan only
Block Sleep : unChecked
Fastboot : Minimal
Virtualization : Enable
VT Fot Direct I/O : unChecked
ASPM : Auto

**Comment by liuaerostone** [comment]
感谢，请问cfglock是怎么解决的呢？刷bios么？

**Comment by liuaerostone** [comment]
> > 一直失败，怀疑是bios设置的问题，有什么注意事项么
> 
> 我的BIOS，供参考
> 
> SATA Operation : AHCI
> Integrated NIC : Enabled
> Secure Boot Enable : unChecked
> Secure Boot Mode : Audit Mode
> SGX : Disabled
> SpeedStep : Enable
> C-States Control : Checked
> Turboost : Enable
> HyperThread Control : Enable
> Intel Speed Shift Technology : Enable
> Deep Sleep Control : Disabled
> USB Wake Support : unChecked
> Wake on LAN/WLAN : Lan only
> Block Sleep : unChecked
> Fastboot : Minimal
> Virtualization : Enable
> VT Fot Direct I/O : unChecked
> ASPM : Auto

衷心感谢，太详细了

**Comment by xuewei8829** [comment]
> > 点关机，CPU风扇狂转，不断电。
> 
> 我整了一个关机补丁，试一下
> [SSDT-SHUT.zip](https://github.com/3dudu/dell-optiplex-7080-hackintosh-opencore/files/5648354/SSDT-SHUT.zip)
> 
> 同时要在config里面改名：
> Find: 5F50545301
> Replace: 5A50545301
> ![螢幕截圖 2020-12-06 下午1 46 49](https://user-images.githubusercontent.com/75524639/101272701-94d6ee80-37c9-11eb-9dbf-22821740a3a1.png)
> 
> ps。我是7080mt

同时要在config里面改名： 这个改名是在哪里修改的呢 用哪个软件可以操作。我用OpenCore Configurator 在ACPI里面新增 在补丁里面查找和替换哪些吗？

**Comment by ghost** [comment]
> > > 点关机，CPU风扇狂转，不断电。
> > 
> > 
> > 我整了一个关机补丁，试一下
> > [SSDT-SHUT.zip](https://github.com/3dudu/dell-optiplex-7080-hackintosh-opencore/files/5648354/SSDT-SHUT.zip)
> > 同时要在config里面改名：
> > Find: 5F50545301
> > Replace: 5A50545301
> > ![螢幕截圖 2020-12-06 下午1 46 49](https://user-images.githubusercontent.com/75524639/101272701-94d6ee80-37c9-11eb-9dbf-22821740a3a1.png)
> > ps。我是7080mt
> 
> 同时要在config里面改名： 这个改名是在哪里修改的呢 用哪个软件可以操作。我用OpenCore Configurator 在ACPI里面新增 在补丁里面查找和替换哪些吗？

对。我发了一张图的。

**Comment by xuewei8829** [comment]
图片打不开了，我也弄过好像不生效------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;mllllll&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年12月12日(星期六) 晚上7:10
收件人:&nbsp;&quot;3dudu/dell-optiplex-7080-hackintosh-opencore&quot;<dell-optiplex-7080-hackintosh-opencore@noreply.github.com&gt;;
抄送:&nbsp;&quot;xuewei8829&quot;<84112497@qq.com&gt;;&quot;Comment&quot;<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [3dudu/dell-optiplex-7080-hackintosh-opencore] 关机还不行 (#2)

**Comment by chaseSpace** [comment]
终于找到7080家族了

**Comment by chaseSpace** [comment]
> > 点关机，CPU风扇狂转，不断电。
> 
> 我整了一个关机补丁，试一下
> [SSDT-SHUT.zip](https://github.com/3dudu/dell-optiplex-7080-hackintosh-opencore/files/5648354/SSDT-SHUT.zip)
> 
> 同时要在config里面改名：
> Find: 5F50545301
> Replace: 5A50545301
> ![螢幕截圖 2020-12-06 下午1 46 49](https://user-images.githubusercontent.com/75524639/101272701-94d6ee80-37c9-11eb-9dbf-22821740a3a1.png)
> 
> ps。我是7080mt

我的还是不行，试过好多次了。。灯不灭

-- 更新
可以了，但我发现了几个问题
### 问题一
反复使用diskgenius修改ESP分区的EFI目录一段时间后，可能会导致BIOS进入opencore引导项后提示
>No bootable devices

**解决**：使用EasyUEFI删掉已有的Opencore引导并重新添加

### 问题二
我使用楼主的EFI不可以重启，现象：点击【重启】后主机灯闪烁橙色一段时间后熄灭。
解决：我另外找了ACPI的文件搞定了。晚点贴地址。

### 问题三
使用楼主的EFI，我的4K显示器最高1080p，找到了方案，还没实践，后续更新。

**Comment by blueskyjeff** [comment]
请问还有什么办法可以修复这个问题么？我试了但不行。。我是双DP的。。能给个具体操作么？看看是不是我操作错误。。谢谢

**Comment by wangyu1221** [comment]
> > 点关机，CPU风扇狂转，不断电。
> 
> 我整了一个关机补丁，试一下
> [SSDT-SHUT.zip](https://github.com/3dudu/dell-optiplex-7080-hackintosh-opencore/files/5648354/SSDT-SHUT.zip)
> 
> 同时要在config里面改名：
> Find: 5F50545301
> Replace: 5A50545301
> ![螢幕截圖 2020-12-06 下午1 46 49](https://user-images.githubusercontent.com/75524639/101272701-94d6ee80-37c9-11eb-9dbf-22821740a3a1.png)
> 
> ps。我是7080mt

升级oc 0.7.1，这个办法好像不行

**Comment by LuckyLyz** [comment]
bios raid on能不改吗，改了win就得重新装

**Comment by 3dudu** [comment]
基本完美了
