### ISSUE TITLE
网卡使用DW1820A可以吗

### ISSUE THREAD

**Issue by xuewei8829** [3dudu/dell-optiplex-7080-hackintosh-opencore#4]
网卡使用DW1820A可以吗
是不是还需要修改主板CFG LOCK和DVMT才能安装呢

**Comment by dankey** [comment]
可以，自带的intel ax201 也能用。

**Comment by xuewei8829** [comment]
201用了有什么问题没有呢。您这边有CFG LOCK和DVMT 修改的参数吗 不能参照7060 7070的去修改吧？

**Comment by 3dudu** [comment]
新传了一个0.6.4分支，是修改了CFG LOCK和DVMT 的，需要用工具U盘启动了改，工具已上传，具体看我参考的原文[https://www.jianshu.com/p/d7cfaae60509]。
CFG Lock 地址是 0x3E，DVMT地址是 0xF5。
7060 7070的方法，用modGRUBShell.efi修改的话应该要支持setup_var_3命令，可是我下到的版本只有setup_var命令，所以用modGRUBShell没有修改成功。
