### ISSUE TITLE
同样有单DP不能输出声音和耳机不能自动切换问题的路过

### ISSUE THREAD

**Issue by lirunext** [3dudu/dell-optiplex-7080-hackintosh-opencore#9]
兄弟，我的也是10代平台，
系统：macOS 11.3.1
机型：HP ProDesk 600 G6 SFF （小型台式机）
芯片组：Q470
CPU：10代 i5-10500
声卡：Realtek ALC222

有和你一样的问题：
“
2.DP不能输出声音，当接两台显示器时，DP声音可以输出。
3.插入耳机，声音输出不能自动切换，需要重开机。当接两台显示器时，耳机声音可以切换。
”
现在还在研究中，我会关注你，看你能不能解决这个问题，如果我先找到解决方法了也来这里贴一下。

**Comment by lirunext** [comment]
另外问下，你的电脑“当接两台显示器时，耳机声音可以切换”，插上耳机后，内置喇叭在声音设置的输出设备列表中会消失吗？我的是会消失的，但我看了白苹果笔记本插上耳机后内置喇叭是不会消失的，系统自动把耳机设为默认输出设备。

**Comment by lirunext** [comment]
问题已解决，详见 http://bbs.pcbeta.com/viewthread-1889263-1-1.html

**Comment by susll** [comment]
@lirunext   大佬求个EFI  hp 680 G6 搞了一个月了  没搞定~~

**Comment by 3dudu** [comment]
这个问题已解决，DP支持音频输出，耳机切换通过combjack选择。就是参考上面链接的方法，我已更新EFI
